swagger: "2.0"
info:
  version: 1.0.0
  title: "Vaccine Census"
  description: Project monitoring platform for a community health programme
  termsOfService: http://swagger.io/terms/
  contact:
    name: Roland Oduberu
    email: rolandoduberu@gmail.com
    url: http://vaccine-algorism.herokuapp.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: vaccine-algorism.herokuapp.com
basePath: /api/vi
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /registrations/status:
    post:
      description: Registration status of the community
      operationId: registerStatus
      parameters:
        - name: api_token
          in: formData
          description: api token, should be a hidden field
          required: true
          type: string
      responses:
        200:
          description: Registration status response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /registrations/male:
    post:
      description: Male Registration status of the community
      operationId: registerStatusMale
      parameters:
        - name: api_token
          in: formData
          description: api token, should be a hidden field
          required: true
          type: string
      responses:
        200:
          description: Male Registration status response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /registrations/female:
    post:
      description: Female Registration status of the community
      operationId: registerStatusFemale
      parameters:
        - name: api_token
          in: formData
          description: api token, should be a hidden field
          required: true
          type: string
      responses:
        200:
          description: Female Registration status response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /registrations/today:
    post:
      description: Registration count for today
      operationId: registerCountToday
      parameters:
        - name: api_token
          in: formData
          description: api token, should be a hidden field
          required: true
          type: string
      responses:
        200:
          description: Registration Count response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /registrations/vaccinated_today:
    post:
      description: Total number of vaccinated children
      operationId: vaccinatedChildren
      parameters:
        - name: api_token
          in: formData
          description: api token, should be a hidden field
          required: true
          type: string
      responses:
        200:
          description: Vaccinated Children response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Pet:
    allOf:
      - $ref: '#/definitions/NewPet'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewPet:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string